version: '3.8'

services:
  # PostgreSQL Main Database
  postgres-main:
    image: postgres:16-alpine
    container_name: postgres-main
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # PostgreSQL Secondary (existing container)
  postgres-secondary:
    image: postgres:16-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_secondary_data:/var/lib/postgresql/data
    restart: always

  # Redis Main
  redis-main:
    image: redis:7-alpine
    container_name: redis-main
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # RabbitMQ (existing container)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    restart: always

  # Portainer for Docker Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  postgres_data:
  postgres_secondary_data:
  redis_data:
  rabbitmq_data:
  portainer_data:

networks:
  default:
    external: true
    name: shared_compose_net
