version: '3.8'

services:
  kibana:
    image: kibana:8.11.0
    container_name: kibana-server
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-master:9200
      ELASTICSEARCH_USERNAME: ""
      ELASTICSEARCH_PASSWORD: ""
      SERVER_NAME: kibana-server
      SERVER_HOST: "0.0.0.0"
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - elastic_network
    restart: always
    depends_on:
      - elasticsearch-master

volumes:
  kibana_data:

networks:
  elastic_network:
    external: true
    name: shared_compose_net
