global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-master:9200']
    metrics_path: /_prometheus/metrics

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
