version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.local
      - GF_SMTP_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/etc/grafana/dashboards:ro
    networks:
      - monitoring_network
    restart: always
    depends_on:
      - prometheus

volumes:
  grafana_data:

networks:
  monitoring_network:
    external: true
