version: '3.8'
services:
  rabbitmq:
    # Ganti 'image' dengan 'build' untuk membuat image kustom
    build: .
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      # RABBITMQ_PLUGINS TIDAK PERLU KARENA SUDAH DISET DI DOCKERFILE
      
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data:

networks:
  default:
    external: true
    name: shared_compose_net



  
# services:
  # rabbitmq:
    # # build: .
    # image: heidiks/rabbitmq-delayed-message-exchange:4.0.7-management
    # container_name: rabbitmq
    # restart: unless-stopped
    # hostname: rabbitmq
    # ports:
      # - "5672:5672"
      # - "15672:15672"
      # - "15692:15692"
    # # environment:
      # # RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      # # RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin123}
      # # RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-mysecretcookie}
    # volumes:
      # - rabbitmq_data:/var/lib/rabbitmq
      # #- ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      # #- ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      # #- ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
# 
# volumes:
  # rabbitmq_data:
