version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000" # Agent
      - "9443:9443" # Web UI via HTTPS
      - "9000:9000" # Web UI via HTTP (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - ADMIN_USERNAME=admin.portainer.io
      - ADMIN_PASSWORD=admin.portainer.io
    restart: always
    networks:
      - app_network

volumes:
  portainer_data:

networks:
  app_network:
    driver: bridge
