version: "3.8"

services:
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
